Repository emqx/emqx-rel, pull requests merged in 2020-07, with the labels that each got.

#540 feature(docker): load modules on docker
  bin/emqx
  deploy/docker/README.md
  deploy/docker/docker-entrypoint.sh
Labels: feature

#547 `MASK_CONFIG_FILTER` to configure setting to mask sensitive config
  deploy/docker/README.md
  deploy/docker/docker-entrypoint.sh
Labels: enhancement

#555 feat(exproto): add emqx_exproto for cloud deps
  Makefile
  rebar.config
Labels: feature

#561 fix: fix error for docker
  deploy/docker/docker-entrypoint.sh
Labels: bug
